strategy:
  matrix:
  #  linux:
  #    imageName: 'ubuntu-16.04'
  #    buildType: 'appbundle'
  #    buildOutDir: 'build/app/outputs/bundle/release'
    mac:
      imageName: 'macos-10.13'
      buildType: 'ios'
      buildOutDir: 'build/ipa'

trigger:
- master
- rel/*

pr:
- master
- rel/*

pool:
  vmImage: $(imageName)

steps:
- script: git submodule update --init --recursive
  displayName: 'Update submodules'
- task: DownloadSecureFile@1
  inputs:
    secureFile: "google-services.json"
- task: DownloadSecureFile@1
  inputs:
    secureFile: "GoogleService-Info.plist"
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'developer.p12'
    certPwd: '$(cert-password)'
    keychain: 'temp'
  displayName: 'Install Developer Certificate (iOS)'
  condition: eq(variables['buildType'], 'ios')
- script: sudo gem install fastlane -NV && FASTLANE_PASSWORD="$(FASTLANE_PASSWORD)" FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD="$(FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD)" fastlane produce -u anais@anaisbetts.org -a org.anaisbetts.sirene --skip-itc && fastlane sigh
  displayName: 'Set up provisioning profiles (iOS)'
  condition: eq(variables['buildType'], 'ios')
- script: mv $(Agent.TempDirectory)/google-services.json ./android/app/
  displayName: 'Move Firebase keys into place (Android)'
- script: mv $(Agent.TempDirectory)/GoogleService-Info.plist ./ios/Runner/
  displayName: 'Move Firebase keys into place (iOS)'
- script: ./flutterw doctor
  displayName: 'Set up Flutter'
- script: ./flutterw test
  displayName: 'Flutter Test'
- script: cd ./ios && pod update
  displayName: 'Try to update Cocoapods (iOS)'
  condition: eq(variables['buildType'], 'ios')
- script: ./flutterw build $(buildType)
  displayName: 'Release build'
- script: cd ./ios && xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $PWD/build/Runner.xcarchive && xcodebuild -exportArchive -archivePath $PWD/build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build/ipa/Runner.ipa
  displayName: 'Archive (iOS)'
  condition: eq(variables['buildType'], 'ios')
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'outputs'
    targetPath: '$(buildOutDir)'
