strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'

trigger:
- master
- rel/*

pr:
- master
- rel/*

pool:
  vmImage: $(imageName)

steps:
- script: git submodule update --init --recursive
  displayName: 'Update submodules'
- script: ./flutterw doctor
  displayName: 'Set up Flutter'
- script: ./flutterw test
  displayName: 'Flutter Test'
