name: sirene
description: text to speech for a voiceless tran

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.4.6+23

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_mlkit_language:
    path: vendor/firebase_mlkit_language
  when_rx:
    path: vendor/when-flutter
  cloud_firestore: ^4.5.0
  device_info_plus: ^8.1.0
  firebase_analytics: ^10.2.0
  firebase_auth: ^4.4.0
  firebase_performance: ^0.9.1
  flutter_markdown: ^0.6.14
  flutter_tts: ^3.6.3
  get_it: ^7.2.0
  google_sign_in: ^6.0.2
  package_info_plus: ^3.0.3
  quiver: ^3.2.1
  rxdart: 0.27.7
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0
  pedantic: ^1.11.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/launcher.png"
  adaptive_icon_foreground: "resources/launcher.png"
  adaptive_icon_background: "#1ECFAC"

flutter:
  uses-material-design: true

  fonts:
    - family: GrandHotel
      fonts:
        - asset: resources/GrandHotel-Regular.ttf
          weight: 400
  assets:
    - resources/initial-phrases.json
    - resources/privacy.md
