name: sirene
description: text to speech for a voiceless tran

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.3.4+15

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.12.5
  cupertino_icons: ^0.1.2
  device_info: ^0.4.0+1
  firebase_analytics: ^3.0.3
  firebase_auth: ^0.11.1
  firebase_mlkit_language: ^1.1.2
  firebase_performance: ^0.3.0
  flutter_markdown: ^0.2.0
  flutter_tts: ^0.2.4
  get_it: ^1.0.2
  google_sign_in: ^4.0.2
  jaguar_serializer: ^2.2.12
  package_info: ^0.4.0+2
  quiver: ^2.0.2
  rxdart: ^0.22.0
  sentry: ^2.2.0
  shared_preferences: ^0.5.2
  when_rx:
    path: vendor/when-flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_launcher_icons: "^0.7.0"
  jaguar_serializer_cli: ^2.2.5
  pedantic: ^1.5.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/launcher.png"
  adaptive_icon_foreground: "resources/launcher.png"
  adaptive_icon_background: "#1ECFAC"

flutter:
  uses-material-design: true

  fonts:
    - family: GrandHotel
      fonts:
        - asset: resources/GrandHotel-Regular.ttf
          weight: 400
  assets:
    - resources/initial-phrases.json
    - resources/privacy.md
