name: sirene
description: text to speech for a voiceless tran

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.3.5+16

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: '< 99.0.0'
  cupertino_icons: '< 99.0.0'
  device_info: '< 99.0.0'
  firebase_analytics: '< 99.0.0'
  firebase_auth: '< 99.0.0'
  firebase_mlkit_language:
    path: vendor/firebase_mlkit_language
  firebase_performance: '< 99.0.0'
  flutter_markdown: '< 99.0.0'
  flutter_tts: '< 99.0.0'
  get_it: '< 99.0.0'
  google_sign_in: '< 99.0.0'
  jaguar_serializer: '< 99.0.0'
  package_info: '< 99.0.0'
  quiver: '< 99.0.0'
  rxdart: '< 99.0.0'
  sentry: '< 99.0.0'
  shared_preferences: '< 99.0.0'
  when_rx:
    path: vendor/when-flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_launcher_icons: '< 99.0.0'
  jaguar_serializer_cli: '< 99.0.0'
  pedantic: '< 99.0.0'

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/launcher.png"
  adaptive_icon_foreground: "resources/launcher.png"
  adaptive_icon_background: "#1ECFAC"

flutter:
  uses-material-design: true

  fonts:
    - family: GrandHotel
      fonts:
        - asset: resources/GrandHotel-Regular.ttf
          weight: 400
  assets:
    - resources/initial-phrases.json
    - resources/privacy.md
